<?php
    View::content();
?>
    <h3>Formulario de Registro</h3>
<?= Form::open() ; ?>
    <div class="row">
        <div class="col s6">
            <label for="Nombres">Nombres
                <?= Form::text('profesores.nombres') ;?>
            </label>
        </div>
        <div class="col s6">
            <label for="Apellidos">Apellidos
                <?= Form::text('profesores.apellidos') ; ?>
            </label>
        </div>
    </div>
    <div class="row">
        <div class="col s6">
            <label for="Especialidad">Especialidad
                <?= Form::text('profesores.especialidad') ;?>
            </label>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <?= Form::submit('Enviar','class="btn green"'); ?>
        </div>
    </div>
<?= Form::close(); ?>