    
<?php Load::models('alumnos'); ?> 
<div class="row">
    <?php View::content() ?>
    <h3>Formulario de Registro de Alumnos</h3>
    <?= Form::open(); ?>
        <div class="row">
            <div class="col s6">
                <label for="Nombres">Nombres
                <?= Form::text('alumnos.nombres'); ?></label>
            </div>
            <div class="col s6">
                <label for="Apellidos">Apellidos
                <?= Form::text('alumnos.apellidos'); ?></label>
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                <label for="Edad">Edad
                <?= Form::text('alumnos.edad');?></label>
            </div>
            <div class="col s6">
                <label for="Telefono">Telefono
                <?= Form::text('alumnos.telefono'); ?></label>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <?= Form::hidden('alumnos.id'); ?>
                <?= Form::submit('Guardar', 'class="btn teal"'); ?>
            </div>
        </div>
    <?= Form::close(); ?>
</div>