<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title><?php echo $titulo ?></title>
</head>
<body>
<nav class="blue ligthen-3">
    <ul>
        <li><?php echo Html::link("alumnos","Listado Alumnos") ?></li>
        <li><?php echo Html::link("alumnos/create", "Registro Alumnos") ;?></li>
        <li><?php echo Html::link("profesores","Listado Profesores") ;?></li>        
        <li><?php echo Html::link("profesores/create","Registro Profesores");?></li>
    </ul>
</nav>
<div class="container">
    <?php View::partial('fecha') ?>
    <?php View::content() ?>
</div>
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>